### PR TITLE
Just some tiny fixes

### PR DESCRIPTION
**Pull request by superfr0**
Fixed links and some info due to the rfhackers site changing.  Forgot to push upstream. Meh.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
labeled not labeled

Also, I think just https://scoreboard.rfhackers.com for the scoreboard link, we want them to hit the landing page.

Lastly, is /user the actual link or does that need to be your username?  I can't test right now

**Comment by superfr0** [comment]
Changed link. And /user is the right link when you are logged in
  It's not /yourusername

**Comment by ZeroChaos-** [comment]
Line 17, "labeled"

**Comment by superfr0** [comment]
Never said I could spell

**Comment by ZeroChaos-** [comment]
LGTM, thanks!

**Pull request merged**
